FROM centos:7 as builder
RUN yum install -y maven
RUN yum install -y git
WORKDIR /
#COPY DevopsTest.jar /
EXPOSE 8080
# CMD java -jar DevopsTest.jar
RUN git clone https://github.com/ckannon/devops-test.git
WORKDIR  /devops-test
RUN mvn package 
WORKDIR  /devops-test/target
#CMD java -jar DevopsTest.jar

FROM centos:7
COPY --from=build /devops-test/target/DevopsTest.jar /DevopsTest.jar
CMD java -jar DevopsTest.jar
